# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_auto_20171210_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='music_source',
            new_name='music_account',
        ),
        migrations.AddField(
            model_name='alarm',
            name='music_playlist',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
