# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_auto_20171210_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='music_fade',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='music_vol',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sunrise_brightness',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sunrise_fade',
            field=models.IntegerField(default=30),
        ),
    ]
