# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_auto_20171210_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='alarm',
            name='days',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='music_fade',
            field=models.DurationField(default=datetime.timedelta(0, 30)),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='music_playlist',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='music_vol',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sunrise_brightness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sunrise_fade',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
    ]
