# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_auto_20180102_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='sunrise_color',
            field=models.FloatField(default=0.5),
        ),
    ]
